### PR TITLE
Adds docs and tests 

### PR DESCRIPTION
**Pull request by gagandeepb**
Towards #2.

### CODE REVIEW

**Comment by gagandeepb** [comment]
@acowley : 
Regarding serialisation to JSON, the current state of this library relies on converting `Rec ElField rs` to a plain record (using `fromVinyl`), and then using the plain record's `ToJSON` instance. 
While records with anonymous fields are not tackled yet, what other major additions/changes are needed to bring this library closer to a release-ready form ?

**Comment by acowley** [comment]
You've done a great job with these additions! I don't know how we'd handle anonymous fields; it seems like something you might do differently for different projects (e.g. numbering fields), so it's certainly not a blocker. You should merge this whenever you feel it is ready and release to hackage.

**Comment by gagandeepb** [comment]
Thanks for the feedback! :)
I shall be preparing this for release; could you please turn on Travis-CI for this repository ?

**Comment by acowley** [comment]
I think travis is enabled now, but I haven't made a configuration file for it yet.

**Comment by gagandeepb** [comment]
There is [this config file](https://github.com/VinylRecords/vinyl-generics/blob/master/.travis.yml), but [here](https://travis-ci.org/VinylRecords/vinyl-generics) it still says that "This is not an active repository".
Am I missing something ?

**Comment by acowley** [comment]
The first [travis build](https://travis-ci.com/VinylRecords/vinyl-generics/builds/101477384) passed!

**Comment by acowley** [comment]
Hm. Looks like a travis-ci.org vs travis-ci.com difference. It is now activated on .org, too. Not sure if being activated on both is advisable or even possible, but hopefully it looks right for you now.

**Pull request merged**
